### ISSUE TITLE
Nav Bar unresponsive on Expo app

### ISSUE THREAD

**Issue by Coolpenguinz** [Fire-app/fire-mobile#32]
Today I encountered an issue with the nav bar being unresponsive to presses when working on my local branch. I had been tinkering with how the nav bar was wired up so I thought it must have been on my end. After further examination, I encountered the same issue when running the app from master. 

I was running Fire on the expo app on IOS. When Jacob tried to recreate this issue using an IOS simulator he couldn't. I doubt this is a hardware problem on my end because I have had no issues with my phone having unresponsive spots on the touchscreen. Navigating through the "know your rights" cards still works smoothly.

**Comment by knarangerel** [comment]
Is this issue still active?

**Comment by knarangerel** [comment]
Closing because it seems to have happened only once
