### ISSUE TITLE
Screen container being longer than it should (flex: 0.95 issue)

### ISSUE THREAD

**Issue by khaliunn** [Fire-app/fire-mobile#33]
![Simulator Screen Shot - iPhone 11 Pro - 2020-07-21 at 21 33 45](https://user-images.githubusercontent.com/31663746/88194387-c4b39a00-cc0c-11ea-9868-f772bf085c53.png)

**Comment by kiwansim** [comment]
Resolved by https://github.com/Fire-app/fire-mobile/pull/37
