### ISSUE TITLE
Main tab bar spacing issue on Android

### ISSUE THREAD

**Issue by knarangerel** [Fire-app/fire-mobile#40]
There's an extra spacing from all sides, and the placement of the emergency button looks wrong.

![Screenshot_20200727-230637](https://user-images.githubusercontent.com/31663746/88615566-3605a980-d060-11ea-8457-1e394ebc8d05.jpg)

**Comment by kiwansim** [comment]
Padding at the bottom of main tab bar is fine on iOS because of the black home tab

![Image from iOS (1)](https://user-images.githubusercontent.com/17574626/88701654-4bb6b580-d0d8-11ea-93bf-d29422607916.png)
